name=eva-boxy
version=1.0.0
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=EVA Boxy
paragraph=GUI 
category=Other
url=https://agusevtec.github.io/eva-boxy-sk
architectures=*
includes=evaBoxy.h
depends=eva-core-sk
