name=eva-boxy
version=1.0.0
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=EVA Boxy. 
paragraph=Declarative desktop-style GUI framework driven by physical keypads. Supports SSD1306, SH1106, KS0108, PCD8544, and HD44780 (LCD I2C) controllers.
category=Display
url=https://agusevtec.github.io/eva-boxy
architectures=*
includes=evabBoxy.h
depends=eva-core-sk
