site_name: EVA Boxy
site_description: EVA Boxy
repo_url: https://github.com/agusevtec/eva-boxy
theme: material
docs_dir: 'docs-md'
site_dir: 'docs'
nav:
  - What is it?: index.md
  - Tutorial:
      - Display Driver: tutorial/01-display-driver.md
      - UI Elements: tutorial/02-ui-elements.md
      - Redraw at position: tutorial/03-user-code-organization.md
      - Keyboard behavior: tutorial/04-keyboard-behavior.md
      - Custom display: tutorial/05-custom-display-driver.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
  - mkdoxy:
      projects:
        eva-boxy:
          src-dirs: ./src
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.h"
            RECURSIVE: True
            EXTRACT_ALL: NO 
            EXTRACT_STRUCT: NO
            EXTRACT_PRIVATE: NO
            EXTRACT_STATIC: YES

